# Generated by Django 3.1.3 on 2020-12-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_auto_20201130_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='Cheese.png', upload_to='pizzas'),
        ),
        migrations.AddField(
            model_name='topping',
            name='image',
            field=models.ImageField(default='Pepperoni.png', upload_to='toppings'),
        ),
    ]
